name: Cache Simulator CI

on:
  push:
  pull_request:

jobs:
  sweep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run quick policy sweep
        run: |
          python run_sweeps.py policies --n 3000

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: cache-sim-results
          path: |
            outputs/results.csv
            outputs/summary.txt
            outputs/events.csv
