name: Lint & Smoke Test

on:
  pull_request:
  push:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ruff + project deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ruff lint (auto-fix, then verify)
        run: |
          ruff --version
          ruff check . --fix
          ruff check .

      - name: Smoke test (quick run)
        run: |
          python run_experiments.py --sweep --n 500
