name: Lint & Smoke Test

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install "ruff>=0.5"  # uses [lint] table in ruff.toml
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ruff lint (auto-fix, then verify)
        run: |
          ruff --version
          ruff check . --fix
          ruff check .

      - name: Smoke test (n=500)
        run: |
          python run_experiments.py --levels 2 --l1_policy LRU --l2_policy LRU --n 500
          test -s outputs/results.csv
          test -s outputs/events.csv
